-- Create styles table
create table styles (
  id uuid default gen_random_uuid() primary key,
  style_id text unique not null,
  name text not null,
  description text not null,
  prompt_modifier text not null,
  icon text not null,
  color text not null,
  is_active boolean default true,
  sort_order int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table styles enable row level security;

-- Anyone can read active styles
create policy "Anyone can view active styles"
on styles for select
using (is_active = true);

-- Service role can manage styles
create policy "Service role can manage styles"
on styles for all
to service_role
using (true)
with check (true);

-- Insert existing styles
insert into styles (style_id, name, description, prompt_modifier, icon, color, sort_order) values
('vesikalik', 'Vesikalık', 'Resmi belgeler için klasik mavi arka planlı vesikalık fotoğraf tarzı.', 'A centered portrait of a man against a solid blue background with a gentle gradient (slightly darker at the bottom, lighter at the top). Expression is neutral and formal, looking directly at the camera. The lighting is bright, soft, and evenly distributed, similar to a Turkish ID/passport photo. Shoulders visible, head fully centered, no dramatic shadows, no artistic effects. Simple, clean, official studio portrait style.', '👔', '#1d4ed8', 1),
('bulut', 'Bulut', 'Mavi gökyüzü ve beyaz bulutlar önünde neşeli bir kolaj.', 'A collage features six different images of the same person with a fair skin tone and dark hair, set against a backdrop of a bright blue sky with scattered white clouds. With a prominent smile in most of the shots. In the largest and most prominent image, located in the bottom right, the person is shown in a close-up from the chest up, laughing heartily, with his mouth open and teeth visible. His expression is one of genuine amusement. Three smaller, full-body images are positioned across the bottom of the collage, showing the person seated outdoors on what appears to be a bench or ledge. In the bottom left image, person is sitting upright, smiling broadly with his hands resting in his lap. In the center bottom image, person is doubled over in laughter, covering its face with both hands, suggesting a moment of intense, possibly overwhelming, humor. In the bottom right of the seated trio, person is again smiling, slightly more reserved than the large close-up, with a similar posture to the bottom left image. Two further, medium-sized, smiling headshots/bust shots are positioned in the top left and top right, slightly faded or set back compared to the others, adding depth to the collage. The top right image is angled slightly differently. The setting suggested by the seated images—a bright, open area—is entirely replaced by the highly visible, slightly artificial-looking cloudscape, creating a surreal or dreamlike composition. The focus is entirely on the person''s emotional reactions, particularly laughter.', '☁️', '#0ea5e9', 2),
('gryffindor', 'Gryffindor', 'Kırmızı ve altın renkli sancaklarla büyüleyici Hogwarts atmosferi.', 'A full-body, indoor photo of a young adult male with fair skin and dark brown hair, standing centered in front of a red and gold banner. He appears to be in his late 20s or early 30s, with a short, trimmed beard of the same dark brown color as his hair. His hair is styled neatly, slightly parted on the side. He is wearing a white athletic jacket with a black zipper down the front and a black Nike swoosh logo on the left chest. The jacket has black piping along the zipper and collar. Underneath the jacket, he is wearing a dark garment visible at the neck. He is also wearing black athletic pants and white sneakers. His posture is upright, with his hands clasped together in front of him at waist level, possibly holding a small item or just resting them. He is looking directly at the camera with a slight, friendly smile. The background consists of a large banner primarily in red and gold, featuring a crest with a lion and possibly other mythical creatures. The word "GRYFFINDOR" is visible in an arc above the crest, suggesting the banner is related to the Harry Potter series. To the right of the Gryffindor banner, a partial view of another flag or banner, possibly Turkish based on the red color and visible star and crescent outline, is seen. The wall behind the subject and the ground beneath him are a light gray or white color, possibly concrete, and the lighting is even but slightly washed out, giving the photo a somewhat vintage or low-quality appearance.', '🏰', '#b91c1c', 3),
('osmanli', 'Osmanlı', 'Geleneksel Osmanlı minyatür sanatı, düz perspektif ve zengin motifler.', '2D Ottoman miniature illustration style. Highly detailed and ornate with vibrant and symbolic color use. Follows flat perspective with no realistic shadows. Richly patterned ornamental borders. Includes swirling decorative motifs such as stylized smoke clouds and floral arabesques. The aesthetic merges classical Ottoman manuscript art with contemporary visual cues in a harmonious and elegant composition. Figures are drawn in graceful, symbolic poses. Visual storytelling is emphasized through pattern, symmetry, and cultural iconography. All elements reflect the traditional aesthetic logic of miniature painting, adapted for modern symbolic expression.', '🕌', '#b45309', 4),
('asker', 'Asker', '90''lar Türk askeri fotoğraf stüdyosu estetiği, kamuflaj, mavi bere ve dramatik bayrak arka planı.', 'A surreal and kitschy digital collage inspired by 90s Turkish military photo studio posters. A man is posing like a conscripted commando, holding a rifle, wearing camouflage pants and a blue beret with a Turkish crescent-star insignia. The background includes a red sky, dramatic Turkish flag overlays, ghostly glowing man eyes in the sky, and over-saturated color grading. A copy of man stand around in macho poses, and some ticks are crawling near their feet. The tone is absurd, emotional, nostalgic, and heroic.', '🪖', '#065f46', 5),
('devrimci', 'Devrimci', 'İkonik, siyah-beyaz ve karizmatik devrimci poster estetiği.', 'A powerful and iconic revolutionary portrait shot with a 40–50 mm lens. The subject looks slightly up at the camera, chin slightly raised, with a determined and stern expression looking towards distant horizons. Half portrait framed at shoulder level. Wearing a dark, military-style collared jacket. Long, wavy hair moving very slightly with the wind. Wearing a simple beret with a round rim and a small, single metal star detail on the beret. Background is neutral and slightly grainy; dramatic, low contrast, black and white film look. Slight beard shadow on the face, iconographic poster aesthetic, strong shadow distribution, revolutionary and charismatic aura.', '⭐', '#44403c', 6),
('anime', 'Anime', 'Canlı renkler ve keskin hatlarla Japon animasyon stili.', 'anime style, cel shaded, vibrant, japanese animation, studio ghibli inspired, detailed line work', '✨', '#3b82f6', 7),
('arabesk', 'Arabesk', '90''lar arabesk albüm kapağı estetiği, dramatik ve nostaljik.', 'A hyper-kitsch 90s Turkish arabesk album cover, extremely dramatic and over-the-top. Yüzünde hüzünlü bir ifade ağlamaklı. Sağa doğru uzaklara bakıyor. Kaşlar kalkık. A foreign popstar styled like a Turkish arabesk singer from the VHS era, posing with dead-serious expression against an artificially vibrant, airbrushed gradient background (neon blue to purple). Giant yellow block letters with thick red outline for the album title at the bottom. Upper left corner features a retro, fake music label logo. The singer wears an exaggerated glittery pinstripe suit, shiny shoulder pads, wide collar shirt, oversized patterned tie, plastic-looking fake red carnation on the lapel. Skin retouched to unrealistic smoothness, ultra-saturated colors, heavy sparkle effects on the suit, soft fog glow around the body. Slight halftone texture like a scanned poster. Tespih tutuyor. Overall tone: nostalgic, camp, melodramatic, intentionally low-budget graphic design. Add cheesy sparkle stars around the jacket, subtle VHS noise, faint lens blur, and artificial studio lighting reminiscent of 1989–1998 arabesk album photo sessions. Horizontal format.', '🎤', '#7e22ce', 8),
('tattoo', 'Dövme', 'Gerçekçi kol dövmesi simülasyonu.', 'Generate a photorealistic image of a man with his upper arm clearly visible in the frame. The man must be present and recognizable in the shot, not cropped out or only partially shown — the upper body and arm should be in full view. Create a realistic tattoo on his arm composed of thin, vein-like branching lines, as if inked naturally into the skin. Integrate a short Turkish extra dramatic and silly quote into the tattoo design, making the text look naturally tattooed — no glow, no fantasy effects, no surreal colors, no exaggerated lighting. The result must look like a real-life photograph of a person with a healed, sharp and believable tattoo on his arm', '💪', '#57534e', 9);
